_BASE_: "./Base-RCNN-C4.yaml"
# OUTPUT_DIR: "output/test_cov"
# OUTPUT_DIR: "output/test_cov2"
# OUTPUT_DIR: "output/test_cov_temp1"
# OUTPUT_DIR: "output/test_prob_early"
# OUTPUT_DIR: "output/test_prob_nll"
# OUTPUT_DIR: "output/at_scaled"
# OUTPUT_DIR: "output/test_iou_select_080"
OUTPUT_DIR: "output/test_v2_nom"
# OUTPUT_DIR: "output/test_align_dgx"
# OUTPUT_DIR: "output/test_v2_iou70_test"
INPUT:
  CLEAN_DETECTIONS: False
  MAX_OCCLUSION: 0.5
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: (550,)
  USE_RANDOM_NOISE: True
  DINO_PATCH_SIZE: 14
  PAD_CROP: True
MODEL:
  PIXEL_STD: [1., 1., 1.]
  # PIXEL_STD: [57.375, 57.120, 58.395]
  # META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  META_ARCHITECTURE: "ProbDATwoStagePseudoLabGeneralizedRCNN"
  # META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  # BACKBONE:
  #   NAME: "build_vgg_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  RPN:
    # IN_FEATURES: ["vgg4"]
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
    # PRE_NMS_TOPK_TRAIN: 6000
    # POST_NMS_TOPK_TRAIN: 1000
  ROI_HEADS:
    # NAME: "StandardROIHeadsPseudoLab"
    NAME: "ProbROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 8
    # IN_FEATURES: ["vgg4"]
    BATCH_SIZE_PER_IMAGE: 512
    # BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    # SMOOTH_L1_BETA: 1.0
    SMOOTH_L1_BETA_PROB: 3.0
  PROBABILISTIC_MODELING:
  # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
    BBOX_COV_LOSS:
        NAME: 'energy_loss'
        # NAME: 'negative_log_likelihood'
        COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
        NUM_SAMPLES: 1000
        # NAME: 'energy_loss2'
        # # NAME: 'negative_log_likelihood'
        # COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
        # NUM_SAMPLES: 50
    ANNEALING_STEP: 10000
    PROB_IOU: True
    SELECT_IOU: False
    SELECT_IOU2: False
    SCALE_LOSS: False
    SCALE_EXPO_SCORE: 1.0
    SCALE_EXPO_IOU: 1.0
    GT_INJECT_COV_WEIGHT: 1.0
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  # STEPS: (60000, 80000, 90000, 360000)
  STEPS: (30000, 35000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  # MAX_ITER: 100000
  MAX_ITER: 40000
  # IMG_PER_BATCH_LABEL: 16
  # IMG_PER_BATCH_UNLABEL: 16
  IMG_PER_BATCH_LABEL: 2
  IMG_PER_BATCH_UNLABEL: 2
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_fine_instance_seg_train",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  # BBOX_THRESHOLD: 0.15
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  # BURN_UP_STEP: 1
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "res4" #["concate","p2","multi"]
  DOMAIN_ADV_INST: 0.0
  # DOMAIN_ADV_INST: 1.0
  ALIGN_PROPOSALS: False
  # ALIGN_LOSS: "MMD"
  ALIGN_LOSS: "contrast"
  ALIGN_WEIGHT: 0.10
  ALIGN_PARAM: 0.07
  ALIGN_PARAM_BASE: 0.07
  ALIGN_INTRA: True
  ALIGN_NORMED: True
  ALIGN_SUBSAMPLING: "random"
  ALIGN_USE_BG: False
  ALIGN_POINTS_PER_PROPOSALS: 10
  ALIGN_QUEUE_LENGHT: 200
  ALIGN_MAX_BATCH: 200
  ALIGN_SCALE_COUNT: False
  ALIGN_BASE_COUNT: 200
  USE_GT_PROPOSALS: False
  USE_GT_PROPOSALS_ONLY: False
  ALIGN_USE_NEGATIVES: False
  ALIGN_GT_PROPOSALS: False
  ALIGN_USE_PROJ: True
  ALIGN_PROTOTYPES: False
  ALIGN_SOURCE_PROT_ONLY: False
  BOX_NORM_CLASS: False
  EVAL_PSEUDO_LABELS: True
  USE_DINO: True
  DINO_LOSS_WEIGHT: 1.0
  DINO_LOSS_WEIGHT_TARGET: 1.0
  DINO_SOURCE_BG_WEIGHT: 0.2
  DINO_SOURCE_FG_THRESH: 0.2
TEST:
  EVAL_PERIOD: 2500
  # EVAL_PERIOD: 2



