_BASE_: "./Base-RCNN-DINO.yaml"
# OUTPUT_DIR: "output/test_cov"
# OUTPUT_DIR: "output/test_cov2"
# OUTPUT_DIR: "output/test_cov_temp1"
# OUTPUT_DIR: "output/test_prob_early"
# OUTPUT_DIR: "output/test_prob_nll"
# OUTPUT_DIR: "output/at_scaled"
# OUTPUT_DIR: "output/test_iou_select_080"
OUTPUT_DIR: "output/test_EMA0999"
# OUTPUT_DIR: "output/test_vits_bbone"
# OUTPUT_DIR: "output/test_v2_iou70_test"
INPUT:
  CLEAN_DETECTIONS: False
  MAX_OCCLUSION: 0.5
  CROP:
    ENABLED: True
    # ENABLED: False
  MIN_SIZE_TRAIN: (550,)
  USE_RANDOM_NOISE: False
  DINO_PATCH_SIZE: 14
  PAD_CROP: True
MODEL:
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    # SIZES: [[256]]  # One size for each in feature map
    # SIZES: [[32, 64, 128, 256, 512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  
  RPN:
    IN_FEATURES: ["p1", "p2", "p3", "p4", "p5"]
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
    # PRE_NMS_TOPK_TRAIN: 6000
    # POST_NMS_TOPK_TRAIN: 1000
  ROI_HEADS:
    IN_FEATURES: ["p1", "p2", "p3", "p4"]
    NAME: "StandardROIHeadsPseudoLab"
    # NAME: "ProbROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 8
    # IN_FEATURES: ["vgg4"]
    BATCH_SIZE_PER_IMAGE: 512
    # BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    # SMOOTH_L1_BETA: 1.0
    SMOOTH_L1_BETA_PROB: 3.0
  PROBABILISTIC_MODELING:
  # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
    BBOX_COV_LOSS:
        NAME: 'energy_loss'
        # NAME: 'negative_log_likelihood'
        COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
        NUM_SAMPLES: 1000
        # NAME: 'energy_loss2'
        # # NAME: 'negative_log_likelihood'
        # COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
        # NUM_SAMPLES: 50
    ANNEALING_STEP: 10000
    PROB_IOU: False
    SELECT_IOU: False
    SELECT_IOU2: False
    SCALE_LOSS: False
    SCALE_EXPO_SCORE: 1.0
    SCALE_EXPO_IOU: 1.0
    GT_INJECT_COV_WEIGHT: 1.0
  # WEIGHTS: "/media/marc/data_checks1/R-101.pkl"
  # WEIGHTS: "/media/marc/data_checks1/R-50.pkl"
  # WEIGHTS: "/media/marc/data_checks1/results_dino/cityfog/bl20k/model_0019999.pth"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 40000
  # IMG_PER_BATCH_LABEL: 16
  # IMG_PER_BATCH_UNLABEL: 16
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  # BASE_LR: 0.04
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_fine_instance_seg_train",)
  # TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  # TEST: ("cityscapes_foggy_val",)
  # TRAIN_UNLABEL: ("ACDC_train_night",)
  # TRAIN_UNLABEL: ("ACDC_train_all",)
  TRAIN_UNLABEL: ("BDD_day_train",)
  TEST: ("cityscapes_val","BDD_day_val")
  # TRAIN_LABEL: ("ACDC_train_night",)
  # TRAIN_UNLABEL: ("ACDC_train_night",)
  # TEST: ("ACDC_val_night",)
  # TEST: ("cityscapes_foggy_val002",)
  # TRAIN_UNLABEL: ("cityscapes_foggy_train002",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  # BBOX_THRESHOLD: 0.15
  TEACHER_UPDATE_ITER: 1
  # BURN_UP_STEP: 20000
  BURN_UP_STEP: 2
  EMA_KEEP_RATE: 0.9996
  # EMA_KEEP_RATE: 0.999
  UNSUP_LOSS_WEIGHT: 0.0
  SUP_LOSS_WEIGHT: 1.0
  # DIS_TYPE: "vgg4" #["concate","p2","multi"]
  DIS_TYPE: "p1" #["concate","p2","multi"]
  DIS_LOSS_WEIGHT: 0.0
  DOMAIN_ADV_INST: 0.0
  # DOMAIN_ADV_INST: 1.0
  ALIGN_PROPOSALS: False
  ALIGN_LOSS: "MMD"
  # ALIGN_LOSS: "contrast"
  ALIGN_WEIGHT: 0.10
  ALIGN_PARAM: 0.07
  ALIGN_PARAM_BASE: 0.07
  ALIGN_INTRA: False
  ALIGN_NORMED: False
  # ALIGN_SUBSAMPLING: "random"
  ALIGN_SUBSAMPLING: "centre"
  ALIGN_USE_BG: False
  ALIGN_POINTS_PER_PROPOSALS: 10
  ALIGN_QUEUE_LENGHT: 200
  ALIGN_MAX_BATCH: 200
  ALIGN_SCALE_COUNT: False
  ALIGN_BASE_COUNT: 200
  USE_GT_PROPOSALS: False
  USE_GT_PROPOSALS_ONLY: False
  ALIGN_USE_NEGATIVES: True
  ALIGN_GT_PROPOSALS: False
  ALIGN_USE_PROJ: False
  ALIGN_PROTOTYPES: False
  # ALIGN_PROTOTYPES_ONLY: True
  ALIGN_SOURCE_PROT_ONLY: False
  BOX_NORM_CLASS: False
  EVAL_PSEUDO_LABELS: False
  SUPPRESS_BBOX_CORR: 1.0
  PSEUDO_THRESH_BOTH: False
  PSEUDO_OBJ_THRESH: 1.0
  USE_DINO: True
  DINO_LOSS_WEIGHT: 0.0
  DINO_LOSS_WEIGHT_TARGET: 0.0
  DINO_SOURCE_BG_WEIGHT: 1.0
  DINO_SOURCE_FG_THRESH: 0.2
  DINO_LOSS_NORM: True
  DINO_HEAD: 'MLP'
  DINO_MODEL: "dinov2_vitb14"
  DINO_INSTANCE_MASK: False
  DINO_TARGET_MASK: False
  DINO_ALIGN_LOSS: "similarity"
  DINO_CONT_QUEUE_LENGTH: 4096
  DINO_CONT_TEMP: 0.1
  DINO_CONT_IGNORE_CLOSEST: 2
  FREEZE_POSTPRETRAIN: False
  PRETRAIN_STEPS: 0
  DINO_PROJ_GELU: False
  # DINO_TARGET_PSEUDOGT: /media/marc/data_checks1/acdc/gt_detection_trainval/gt_detection/night/train/dino_anno.pkl
  # DINO_TARGET_PSEUDOGT: /media/marc/data_checks1/cityscapes/gtFine_trainvaltest/gtFine/BDD_day_train_dino_anno.pkl
  DINO_TARGET_PSEUDOGT: None
  # DINO_PSEUDOGT_SWAP: 'half'
  # DINO_PSEUDOGT_SWAP_ITER: 10
  DINO_ALIGN_ONLY_UNTIL: -1
  DINO_ALIGN_EASY_ONLY: True
  DINO_SAM_MASK: False
  DINO_BASE: True
  DINO_LR_SCALE: 0.0
  USE_VITDET: True
TEST:
  EVAL_PERIOD: 2500
  # EVAL_PERIOD: 10



