_BASE_: "./Base-RCNN-C4.yaml"
OUTPUT_DIR: "output/test_cov"
# OUTPUT_DIR: "output/test_cov2"
# OUTPUT_DIR: "output/test_cov_temp1"
INPUT:
  CLEAN_DETECTIONS: False
  MAX_OCCLUSION: 0.5
MODEL:
  # META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  META_ARCHITECTURE: "ProbDATwoStagePseudoLabGeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  RPN:
    IN_FEATURES: ["vgg4"]
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
    # PRE_NMS_TOPK_TRAIN: 6000
    # POST_NMS_TOPK_TRAIN: 1000
  ROI_HEADS:
    # NAME: "StandardROIHeadsPseudoLab"
    NAME: "ProbROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 8
    IN_FEATURES: ["vgg4"]
    BATCH_SIZE_PER_IMAGE: 512
    # BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  PROBABILISTIC_MODELING:
  # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
    BBOX_COV_LOSS:
        NAME: 'energy_loss'
        COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
        NUM_SAMPLES: 1000
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 100000
  # IMG_PER_BATCH_LABEL: 16
  # IMG_PER_BATCH_UNLABEL: 16
  IMG_PER_BATCH_LABEL: 3
  IMG_PER_BATCH_UNLABEL: 3
  BASE_LR: 0.04
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_fine_instance_seg_train",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  # BURN_UP_STEP: 20
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg4" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 1000
  # EVAL_PERIOD: 10
# INPUT:
#   MIN_SIZE_TRAIN: (450,)


